// import React from "react";
// import ReactDOM from "react-dom/client";
// import { Authenticator } from "@aws-amplify/ui-react";
// import App from "./App.jsx";
// import "./index.css";

// ReactDOM.createRoot(document.getElementById("root")).render(
//   <React.StrictMode>
//     <Authenticator>
//       <App />
//     </Authenticator>
//   </React.StrictMode>
// );

// working one down for email
// import React from "react";
// import ReactDOM from "react-dom/client";
// import { Amplify } from "aws-amplify";
// import { Authenticator } from "@aws-amplify/ui-react";
// import App from "./App.jsx";
// import "@aws-amplify/ui-react/styles.css";
// import "./index.css";

// // Load the config generated by Amplify Sandbox/Deploy.
// // Use ONE of the two imports depending on where the file is:
// import outputs from "/amplify_outputs.json";        // absolute from project root
// // import outputs from "../amplify_outputs.json";    // use this if you prefer relative

// Amplify.configure(outputs); // <-- REQUIRED before using <Authenticator/>

// ReactDOM.createRoot(document.getElementById("root")).render(
//   <React.StrictMode>
//     <Authenticator>
//       <App />
//     </Authenticator>
//   </React.StrictMode>
// );


import React from "react";
import ReactDOM from "react-dom/client";
import { Amplify } from "aws-amplify";
import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import App from "./App.jsx";
import "./index.css";

/**
 * Configure Amplify using amplify_outputs.json from either:
 *  - local:   ../amplify_outputs.json (generated by `npx ampx sandbox`)
 *  - hosting: /amplify_outputs.json   (served at site root by Amplify Hosting)
 */
async function loadOutputs() {
  // Vite exposes these flags:
  const isLocal = import.meta.env.DEV || location.hostname === "localhost";

  try {
    // Try relative file first (works in local dev)
    if (isLocal) {
      const outputs = (await import("../amplify_outputs.json")).default;
      Amplify.configure(outputs);
    } else {
      // Hosted: fetch from site root
      const res = await fetch("/amplify_outputs.json");
      const outputs = await res.json();
      Amplify.configure(outputs);
    }
  } catch (e) {
    console.error("Failed to load amplify_outputs.json", e);
  }

  // Choose login mechanism by environment:
  const loginMechanisms = (isLocal ? ["username"] : ["email"]);
  const signUpAttributes = (isLocal ? [] : ["email"]);

  ReactDOM.createRoot(document.getElementById("root")).render(
    <React.StrictMode>
      <Authenticator
        loginMechanisms={loginMechanisms}
        signUpAttributes={signUpAttributes}
      >
        <App />
      </Authenticator>
    </React.StrictMode>
  );
}

loadOutputs();

