// working username and password
import React from "react";
import ReactDOM from "react-dom/client";
import { Authenticator } from "@aws-amplify/ui-react";
import App from "./App.jsx";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <Authenticator>
      <App />
    </Authenticator>
  </React.StrictMode>
);



// working one down for email
// import React from "react";
// import ReactDOM from "react-dom/client";
// import { Amplify } from "aws-amplify";
// import { Authenticator } from "@aws-amplify/ui-react";
// import App from "./App.jsx";
// import "@aws-amplify/ui-react/styles.css";
// import "./index.css";

// // Load the config generated by Amplify Sandbox/Deploy.
// // Use ONE of the two imports depending on where the file is:
// import outputs from "/amplify_outputs.json";        // absolute from project root
// // import outputs from "../amplify_outputs.json";    // use this if you prefer relative

// Amplify.configure(outputs); // <-- REQUIRED before using <Authenticator/>

// ReactDOM.createRoot(document.getElementById("root")).render(
//   <React.StrictMode>
//     <Authenticator>
//       <App />
//     </Authenticator>
//   </React.StrictMode>
// );
